[server]
runOnSave = true
fileWatcherType = "poll"

[client]
showErrorDetails = true

[theme]
primaryColor = "#111827"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9fafb"
textColor = "#111827"
font = "sans serif"

